services:
  node:
    image: node:16-slim
    ports:
      - "127.0.0.1:3000:3000"
    user: node
    working_dir: /home/node/app/src/sms-tsm-linker
    volumes:
      - ./:/home/node/app/
    command:
      - npm
      - run
      - dev
