<template>
  <v-container>
    <v-row justify="center" align="center">
      <v-col cols="12" sm="12" md="12">
        <v-card>
          <v-card-title class="headline">
            Sensor Management System / Time Series Management Linker Proposal
          </v-card-title>
          <v-card-text>
            <p>This is a proposal how a linker module could look like. The aim is to link
              datastreams which are generated by time series management and measurement quantities
              which are defined by the sensor management system.</p>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
    <v-form>
      <v-row>
        <v-col cols="12" sm="12" md="12">
          <v-select
            :value="projects[1].name"
            label="Project"
            :items="projects.map(({name}) => name)"
          />
        </v-col>

        <v-col cols="12" sm="6" md="6">
          <v-select
            :value="sms.instances[1]"
            label="SMS Instance"
            :items="sms.instances"
          />
        </v-col>
        <v-col cols="12" sm="6" md="6">
          <v-select
            :value="tsm.instances[1]"
            label="TSM Instance"
            :items="tsm.instances"
          />
        </v-col>

        <v-col cols="12" sm="6" md="6">
          <v-select :value="projects[1].configurations[1].name" label="Configuration"
                    :items="projects[1].configurations.map(({name}) => name)"/>
        </v-col>
        <v-col cols="12" sm="6" md="6">
          <v-select :value="tsm.things[1].name" label="TSM Thing"
                    :items="tsm.things.map(({name}) => name)"/>
        </v-col>
        <v-col cols="12" sm="6" md="6">

          <v-select :value="projects[1].configurations[1].devices[0]" label="Device"
                    :items="projects[1].configurations[1].devices"/>
        </v-col>
        <v-col cols="12" sm="6" md="6">

          <v-select :value="tsm.things[1].datastreams[1].id" label="Datastream"
                    :items="tsm.things[1].datastreams.map(function(datastream) {
                      return `id: ${datastream.id}, last label: ${datastream.last_label}`
                    })"/>
        </v-col>

        <v-col cols="12" sm="6" md="6">

          <v-select :value="mountPeriods[0]" label="Mount periode"
                    :items="mountPeriods"/>
        </v-col>
        <v-col cols="12" sm="6" md="6">

        </v-col>

        <v-col cols="12" sm="6" md="6">

          <v-select :value="measuredQuantities[0]" label="Measured Quantity"
                    :items="measuredQuantities"/>
        </v-col>
        <v-col cols="12" sm="6" md="6">

        </v-col>

      </v-row>
      <v-btn color="primary">Submit</v-btn>
    </v-form>
  </v-container>
</template>

<script>
export default {
  name: 'IndexPage',
  methods: {},
  data() {
    return {
      mountPeriods: ["2021-11-24 17:33:48 (UTC) - ∞"],
      measuredQuantities: [
        "Measured quantity 1 - Soil Permittivity",
        "Measured quantity 2 - Soil Temperature"
      ],
      projects: [
        {name: 'eLTER', configurations: [{name: 'Biggesee'}]},
        {
          name: 'MOSES',
          configurations: [
            {name: 'Elbe Kampagne 2022'},
            {
              name: 'MOSES_Hitze_Dresden',
              devices: [
                'SMT100 (123456789) (x=2m)',
                'SMT100 (987654321) (y=3m)',
              ],
            },
            {name: 'Messkampagne Friedenspark (FeelGood-Campaign 2021)'}
          ]
        },
        {name: 'EXPRESS', configurations: [{name: 'Biggesee'}]},
        {name: 'CHS Soilnet', configurations: []},
        {name: 'TERENO TOR', configurations: []},
        {name: 'TERENO Cosmic Ray Neutron Sensing CRNS', configurations: []},
      ],
      sms: {
        instances: [
          'sms.gfz.de',
          'webapp-stage.intranet.ufz.de/rdm/svm/',
        ]
      },
      tsm: {
        instances: [
          'tsm.gfz.de',
          'tsm.intranet.ufz.de',
        ],
        things: [
          {uuid: '8d0a324e-b06c-11ec-b88f-9705597c84dc', name: 'CRNS01'},
          {
            uuid: '8d0a3370-b06c-11ec-b890-8716049e009b',
            name: 'CRNS02',
            datastreams:
              [
                {id: 1, last_label: "temp_t100a"},
                {id: 2, last_label: "temp_t100b"},
                {id: 2, last_label: "temp_t100c"},
              ]
          },
          {uuid: '8d0a33ca-b06c-11ec-b891-3fb1b988d397', name: 'CRNS03'},
          {uuid: '8d0a35d2-b06c-11ec-b898-2765e1bdf517', name: 'CRNS04'},
        ]
      },
    }
  },
}
</script>
